public class Multipick {

    public PageReference method() {
        return null;
    }

public List<SelectOption> color{get;set;}
public List<string> Selected{get;set;}
public Multipick() {
color= new list<selectoption>();
Selected = new List<string>();
color.add(new SelectOption('US','US'));
color.add(new SelectOption('Green','GREEN'));
color.add(new SelectOption('Red','RED'));
color.add(new SelectOption('Blue','BLUE'));

}
}